name: McTiersBridge
version: '${version}'
website: https://github.com/ceymikey/McTierBridge
author: ceymikey
description: Bridge between McTiers api and PlaceholderAPI
main: dev.ceymikey.mcTiersBridge.McTiersBridge
api-version: '1.16'
depend: [PlaceholderAPI]